### ISSUE TITLE
Server crashes after visiting home page

### ISSUE THREAD

**Issue by yhg1412** [simpletut/Universal-React-Apollo-Registration#12]
I can bring up the server, but when I try to visit localhost:3000 using my browser, the server crashes and giving me this error:

App running on port 3000
Connection to DB successful
/Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/zen-observable/lib/Observable.js:63
      throw e;
      ^

TypeError: Cannot read property 'delete' of undefined
    at /Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/apollo-link-dedup/lib/dedupLink.js:48:47
    at cleanupSubscription (/Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/zen-observable/lib/Observable.js:90:7)
    at notifySubscription (/Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/zen-observable/lib/Observable.js:145:41)
    at onNotify (/Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.complete (/Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/zen-observable/lib/Observable.js:229:7)
    at /Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/apollo-link-dedup/lib/dedupLink.js:34:81
    at Set.forEach (<anonymous>)
    at Object.next (/Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/apollo-link-dedup/lib/dedupLink.js:34:45)
    at notifySubscription (/Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.next (/Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/zen-observable/lib/Observable.js:219:7)
    at /Users/hugangyu/xuetantan/Universal-React-Apollo-Registration/node_modules/apollo-link-http/lib/bundle.umd.js:95:30
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
[nodemon] app crashed - waiting for file changes before starting...﻿

I'm following the video exactly and I'm using yarn to install and manage packages.

**Comment by simpletut** [comment]
I am closing this issue as I have just verified that the project is working by successfully cloning, installing and running the app.

Please double check your setup to ensure you do not have an error in your configuration.
